name: master_server
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.26.0
  - pandas=2.1.2
  - flask
  - requests=2.31.0
  - scipy=1.11.1
  - scikit-image=0.22.0
  - pymongo
  - pip
  - pip:
      - opencv-python==4.8.1.78
      - gradio==3.38.0
      - flask_limiter
      - apns2